services:
  - type: web
    name: dnd-calculator
    env: node
    plan: free
    buildCommand: npm install && cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview --host
    branch: main